### ISSUE TITLE
I cannot update the admin password or username

### ISSUE THREAD

**Issue by Nmaximillian** [keivanipchihagh/x-ui#10]
When I first deployed the image, the web-ui works well and I can login with the default password but after updating the username/password, it keeps saying it is bad password/username, regardless of whatever password i used

**Comment by keivanipchihagh** [comment]
Hello,
This is a known bug with the original image. I haven't checked if they fixed it in later releases or not. However, after changing your username and password, try with your new username as the username and your old password as the password. It works for me.

**Comment by keivanipchihagh** [comment]
I'm closing this thread. If the problem persists, do reopen the thread.

**Comment by Nmaximillian** [comment]
That's fine, it makes sense now, thanks for the reply.
